# frozen_string_literal: true

module Ieee
  module Idams
    class Error < StandardError; end

    autoload :Address, "ieee/idams/address.rb"
    autoload :Affiliation, "ieee/idams/affiliation.rb"
    autoload :AffiliationAddress, "ieee/idams/affiliation_address.rb"
    autoload :AffiliationGroup, "ieee/idams/affiliation_group.rb"
    autoload :Article, "ieee/idams/article.rb"
    autoload :ArticleAbstract, "ieee/idams/article_abstract.rb"
    autoload :ArticleCopyright, "ieee/idams/article_copyright.rb"
    autoload :ArticleDate, "ieee/idams/article_date.rb"
    autoload :ArticleFilename, "ieee/idams/article_filename.rb"
    autoload :ArticleInfo, "ieee/idams/article_info.rb"
    autoload :ArticlePageNums, "ieee/idams/article_page_nums.rb"
    autoload :Author, "ieee/idams/author.rb"
    autoload :AuthorGroup, "ieee/idams/author_group.rb"
    autoload :ConfGroup, "ieee/idams/conf_group.rb"
    autoload :Copyright, "ieee/idams/copyright.rb"
    autoload :CopyrightGroup, "ieee/idams/copyright_group.rb"
    autoload :IcsCodeTerm, "ieee/idams/ics_code_term.rb"
    autoload :IcsCodes, "ieee/idams/ics_codes.rb"
    autoload :Isbn, "ieee/idams/isbn.rb"
    autoload :Keyword, "ieee/idams/keyword.rb"
    autoload :KeywordSet, "ieee/idams/keyword_set.rb"
    autoload :Multimedia, "ieee/idams/multimedia.rb"
    autoload :MultimediaComponent, "ieee/idams/multimedia_component.rb"
    autoload :MultimediaCompressed, "ieee/idams/multimedia_compressed.rb"
    autoload :PackageMemberSet, "ieee/idams/package_member_set.rb"
    autoload :ProductNumber, "ieee/idams/product_number.rb"
    autoload :PubModel, "ieee/idams/pub_model.rb"
    autoload :PubSponsor, "ieee/idams/pub_sponsor.rb"
    autoload :PubSponsoringCommitteeSet,
             "ieee/idams/pub_sponsoring_committee_set.rb"
    autoload :PubTopicalBrowseSet, "ieee/idams/pub_topical_browse_set.rb"
    autoload :Publication, "ieee/idams/publication.rb"
    autoload :PublicationAcronym, "ieee/idams/publication_acronym.rb"
    autoload :PublicationInfo, "ieee/idams/publication_info.rb"
    autoload :Publisher, "ieee/idams/publisher.rb"
    autoload :StandardBundle, "ieee/idams/standard_bundle.rb"
    autoload :StandardModifierSet, "ieee/idams/standard_modifier_set.rb"
    autoload :StandardPackageSet, "ieee/idams/standard_package_set.rb"
    autoload :StandardRelationship, "ieee/idams/standard_relationship.rb"
    autoload :Volume, "ieee/idams/volume.rb"
    autoload :VolumeInfo, "ieee/idams/volume_info.rb"
    autoload :VolumeInfoIssue, "ieee/idams/volume_info_issue.rb"
    autoload :VolumeNoteGroup, "ieee/idams/volume_note_group.rb"
  end
end
